/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Calculadora;
import util.Arquivo;

/**
 *
 * @author Alex
 */
public class view extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    public view() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTFValor1 = new javax.swing.JTextField();
        JTFValor2 = new javax.swing.JTextField();
        JTFResultado = new javax.swing.JTextField();
        ButtonDividir = new javax.swing.JButton();
        ButtonLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTAHistorico = new javax.swing.JTextArea();
        ButtonLimpar2 = new javax.swing.JButton();
        ButtonMultiplicar = new javax.swing.JButton();
        ButtonSomar = new javax.swing.JButton();
        ButtonSubtrair1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("numero 1");

        jLabel2.setText("numero 2");

        JTFValor1.setBackground(new java.awt.Color(0, 0, 0));
        JTFValor1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JTFValor1.setForeground(new java.awt.Color(255, 255, 255));
        JTFValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFValor1ActionPerformed(evt);
            }
        });

        JTFValor2.setBackground(new java.awt.Color(0, 0, 0));
        JTFValor2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JTFValor2.setForeground(new java.awt.Color(255, 255, 255));

        JTFResultado.setBackground(new java.awt.Color(0, 0, 0));
        JTFResultado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JTFResultado.setForeground(new java.awt.Color(255, 255, 255));
        JTFResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFResultadoActionPerformed(evt);
            }
        });

        ButtonDividir.setBackground(new java.awt.Color(0, 0, 0));
        ButtonDividir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonDividir.setForeground(new java.awt.Color(255, 255, 255));
        ButtonDividir.setText("dividir");
        ButtonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDividirActionPerformed(evt);
            }
        });

        ButtonLimpar.setBackground(new java.awt.Color(0, 0, 0));
        ButtonLimpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonLimpar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLimpar.setText("Limpar");
        ButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLimparActionPerformed(evt);
            }
        });

        JTAHistorico.setBackground(new java.awt.Color(0, 0, 0));
        JTAHistorico.setColumns(20);
        JTAHistorico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JTAHistorico.setForeground(new java.awt.Color(255, 255, 255));
        JTAHistorico.setRows(5);
        jScrollPane1.setViewportView(JTAHistorico);

        ButtonLimpar2.setBackground(new java.awt.Color(0, 0, 0));
        ButtonLimpar2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonLimpar2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLimpar2.setText("limpar H");
        ButtonLimpar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLimpar2ActionPerformed(evt);
            }
        });

        ButtonMultiplicar.setBackground(new java.awt.Color(0, 0, 0));
        ButtonMultiplicar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonMultiplicar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonMultiplicar.setText("multiplicar");
        ButtonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMultiplicarActionPerformed(evt);
            }
        });

        ButtonSomar.setBackground(new java.awt.Color(0, 0, 0));
        ButtonSomar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonSomar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonSomar.setText("somar");
        ButtonSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSomarActionPerformed(evt);
            }
        });

        ButtonSubtrair1.setBackground(new java.awt.Color(0, 0, 0));
        ButtonSubtrair1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonSubtrair1.setForeground(new java.awt.Color(255, 255, 255));
        ButtonSubtrair1.setText("subtrair");
        ButtonSubtrair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSubtrair1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                            .addComponent(JTFResultado)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(JTFValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButtonSubtrair1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonLimpar))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonMultiplicar)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonLimpar2)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonSomar))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ButtonMultiplicar)
                                    .addComponent(ButtonDividir)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonLimpar)
                            .addComponent(ButtonLimpar2)))
                    .addComponent(ButtonSubtrair1))
                .addGap(10, 10, 10)
                .addComponent(JTFResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFValor1ActionPerformed

    private void ButtonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDividirActionPerformed
        // TODO add your handling code here:
        if(JTFValor1.getText().trim().isEmpty() || JTFValor2.getText().trim().isEmpty()){
            JTFResultado.setText("Preencha todos os campos");
            JTAHistorico.setText("preencha todos os campos");
            JTFValor1.requestFocus();
            return;
        }
        try{
            double num1 = Double.parseDouble(JTFValor1.getText());
            double num2 = Double.parseDouble(JTFValor2.getText());
            
            Calculadora calculadora = new Calculadora();
            double resultado = calculadora.dividir(num1,num2);
            
            JTFResultado.setText("resultado: "+ resultado);
            
            JTAHistorico.append(num1 + " / " + num2 +" = " + resultado + "\n");
            String linha = num1 + " / " + num2 + " = " + resultado;
            Arquivo.salvarLinha(linha);
        }
        catch(NumberFormatException ex){
            JTFResultado.setText("digite apenas valor numerico");
        }
        catch(ArithmeticException ex){
            JTFResultado.setText(ex.getMessage());
        }
          
    }//GEN-LAST:event_ButtonDividirActionPerformed

    private void ButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLimparActionPerformed
        // TODO add your handling code here:
        
        JTFValor1.setText("");
        JTFValor2.setText("");
        JTFResultado.setText("");
        JTFValor1.requestFocus(); 
    }//GEN-LAST:event_ButtonLimparActionPerformed

    private void JTFResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFResultadoActionPerformed

    private void ButtonLimpar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLimpar2ActionPerformed
        // TODO add your handling code here:
        JTAHistorico.setText("");
        JTFValor1.requestFocus();
        
    }//GEN-LAST:event_ButtonLimpar2ActionPerformed

    private void ButtonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMultiplicarActionPerformed
        // TODO add your handling code here:
        if(JTFValor1.getText().trim().isEmpty() || JTFValor2.getText().trim().isEmpty()){
            JTFResultado.setText("Preencha todos os campos");
            JTAHistorico.setText("preencha todos os campos");
            JTFValor1.requestFocus();
            return;
        }
        try{
            double num1 = Double.parseDouble(JTFValor1.getText());
            double num2 = Double.parseDouble(JTFValor2.getText());
            
            Calculadora calculadora = new Calculadora();
            double resultado = calculadora.multiplicar(num1,num2);
            
            JTFResultado.setText("resultado: "+ resultado);
            
            JTAHistorico.append(num1 + " x " + num2 +" = " + resultado + "\n");
            String linha = num1 + " * " + num2 + " = " + resultado;
            Arquivo.salvarLinha(linha);
        }
        catch(NumberFormatException ex){
            JTFResultado.setText("digite apenas valor numerico");
        }
        catch(ArithmeticException ex){
            JTFResultado.setText(ex.getMessage());
        }
        
        
    }//GEN-LAST:event_ButtonMultiplicarActionPerformed

    private void ButtonSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSomarActionPerformed
        // TODO add your handling code here:
        if(JTFValor1.getText().trim().isEmpty() || JTFValor2.getText().trim().isEmpty()){
            JTFResultado.setText("Preencha todos os campos");
            JTAHistorico.setText("preencha todos os campos");
            JTFValor1.requestFocus();
            return;
        }
        try{
            double num1 = Double.parseDouble(JTFValor1.getText());
            double num2 = Double.parseDouble(JTFValor2.getText());
            
            Calculadora calculadora = new Calculadora();
            double resultado = calculadora.somar(num1,num2);
            
            JTFResultado.setText("resultado: "+ resultado);
            
            JTAHistorico.append(num1 + " + " + num2 +" = " + resultado + "\n");
            String linha = num1 + " + " + num2 + " = " + resultado;
            Arquivo.salvarLinha(linha);
        }
        catch(NumberFormatException ex){
            JTFResultado.setText("digite apenas valor numerico");
        }
        catch(ArithmeticException ex){
            JTFResultado.setText(ex.getMessage());
        }
    }//GEN-LAST:event_ButtonSomarActionPerformed

    private void ButtonSubtrair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSubtrair1ActionPerformed
        // TODO add your handling code here:
        if(JTFValor1.getText().trim().isEmpty() || JTFValor2.getText().trim().isEmpty()){
            JTFResultado.setText("Preencha todos os campos");
            JTAHistorico.setText("preencha todos os campos");
            JTFValor1.requestFocus();
            return;
        }
        try{
            double num1 = Double.parseDouble(JTFValor1.getText());
            double num2 = Double.parseDouble(JTFValor2.getText());
            
            Calculadora calculadora = new Calculadora();
            double resultado = calculadora.subtrair(num1,num2);
            
            JTFResultado.setText("resultado: "+ resultado);
            
            JTAHistorico.append(num1 + " - " + num2 +" = " + resultado + "\n");
            String linha = num1 + " - " + num2 + " = " + resultado;
            Arquivo.salvarLinha(linha);
        }
        catch(NumberFormatException ex){
            JTFResultado.setText("digite apenas valor numerico");
        }
        catch(ArithmeticException ex){
            JTFResultado.setText(ex.getMessage());
        }
    }//GEN-LAST:event_ButtonSubtrair1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDividir;
    private javax.swing.JButton ButtonLimpar;
    private javax.swing.JButton ButtonLimpar2;
    private javax.swing.JButton ButtonMultiplicar;
    private javax.swing.JButton ButtonSomar;
    private javax.swing.JButton ButtonSubtrair1;
    private javax.swing.JTextArea JTAHistorico;
    private javax.swing.JTextField JTFResultado;
    private javax.swing.JTextField JTFValor1;
    private javax.swing.JTextField JTFValor2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
